version: '3.6'

services:
                 
  database:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/secret
    volumes:
      - type: volume
        source: easymoto_db
        target: /data
        volume:
          nocopy: true

  backend:
    image: org.easymoto/easymoto-backend:0.0.1
    depends_on:
      - database
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: /opt/easymoto/config
        target: /config
          
volumes:
  easymoto_db:
    external: true