FROM openjdk:8-jre-alpine3.7
VOLUME /tmp
VOLUME /config
ADD easymoto-backend-0.0.1.jar app.jar
EXPOSE 8080
RUN sh -c 'touch /app.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar", "--spring.config.location=file:/config/application.properties" ]