pipeline {
    agent any
    stages {
        stage('Checkout'){
            steps {
                echo 'Checkout Project'
                checkout scm
            }
        }
        
        stage('Build'){
            steps {
                echo 'Checkout Project'
                dir('easymoto-backend'){
                	sh './gradlew clean build -x test'
        		}
            }
        }
        
        stage('Test'){
            steps {
                echo 'Testing'
                dir('easymoto-backend'){
                	sh './gradlew test'
                	junit 'build/test-results/test/*.xml'
        		}
            }
        }
        
    }
    
    post {
    
        always {
            echo 'Esse texto será impresso sempre ao final !'
        }
    }
}
